# Use Node.js base image
FROM node:14 as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy application source code
COPY . .

# Build the React application
RUN npm run build

# Use Nginx to serve the built static files
FROM nginx:alpine

# Copy the built files from the build stage to Nginx's serve directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Set the command to start Nginx
CMD ["nginx", "-g", "daemon off;"]