name: CD

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
  CLOUD_RUN_SERVICE: ${{ secrets.CLOUD_RUN_SERVICE }}
  REGION: us-central1

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm ci
    - name: Build React app
      run: npm run build
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Deploy to GCS
      run: |
        gsutil -m rsync -r build gs://$GCS_BUCKET
    - name: Configure Cloud CDN
      run: |
        gcloud compute backend-buckets update $GCS_BUCKET --enable-cdn

  deploy_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Build and deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$CLOUD_RUN_SERVICE
        gcloud run deploy $CLOUD_RUN_SERVICE --image gcr.io/$PROJECT_ID/$CLOUD_RUN_SERVICE --platform managed --region $REGION

  update_database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Run database migrations
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Add the appropriate command to run database migrations
        # For example: python manage.py migrate
        echo "Run database migrations here"

  notify_team:
    needs: [deploy_frontend, deploy_backend, update_database]
    runs-on: ubuntu-latest
    steps:
    - name: Notify team
      # HUMAN ASSISTANCE NEEDED
      # Add the appropriate notification method (e.g., Slack, email)
      run: |
        echo "Notify team about successful deployment"